<a href="https://colab.research.google.com/github/ShrikantBKumbhar/shrikx_datasci/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4,5]

In [ ]:
arr = np.array(l) #converts list to 1 d array

In [ ]:
type(arr) # n dimentional array

numpy.ndarray

In [ ]:
np.asarray(l) #same as array

array([1, 2, 3, 4, 5])

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]]) #output will be 2 d array

In [ ]:
arr.ndim #displays dimentions of array

1

In [ ]:
arr1.ndim #displays dimentions of array

2

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
mat = np.matrix(l) # this return by default 2 dim array cos matrix has default 2 dim only - matrix is a type of array

In [ ]:
mat.ndim

2

In [ ]:
np.asanyarray(l) #converts to array

array([1, 2, 3, 4, 5])

In [ ]:
np.asanyarray(mat) # since matrix is one kind of array so it wont convert 

matrix([[1, 2, 3, 4, 5]])

In [ ]:
arr[0] = 101

In [ ]:
arr

array([101,   2,   3,   4,   5])

In [ ]:
a = arr #this type of data copy is called as solo copy, it just creates only reference to the data, no seperate memory location - any changes will be reflect in both a and arr

In [ ]:
a

array([101,   2,   3,   4,   5])

In [ ]:
b = np.copy(arr) # this will create different memory location - this is dip copy

In [ ]:
b

array([101,   2,   3,   4,   5])

In [ ]:
b[0] = 201

In [ ]:
b # b has changed but not arr since both have diff memory location

array([201,   2,   3,   4,   5])

In [ ]:
arr # b has changed but not arr since both have diff memory location

array([101,   2,   3,   4,   5])

In [ ]:
np.fromfunction(lambda i,j : i == j, (3,3)) # this function takes another function as an argument and based on that func (here lambda) it generate data set 
# i, j are input, i = j is expression, and (3,3) is shape of output array - i = row, j = column
#it compare i and j with each other as per expression based on x and y coordinates from array shape
#   i/j     0       1       2

#   0       T       F       F

#   1       F       T       F

#   2       F       F       T 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i+j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [ ]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
(i*i for i in range(5)) #comprehension operation - shorter syntax

<generator object <genexpr> at 0x7f81b0b25b30>

In [ ]:
list((i*i for i in range(5))) #store in list - same thing can be executed using numpy as below using 'fromiter' function which generates data set as an array

[0, 1, 4, 9, 16]

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float) #takes iterable as an 1st argument and dtype as 2nd

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('25 30 80 40',sep = ' ') # takes string and seperator as an arguments

array([25., 30., 80., 40.])

In [ ]:
arr

array([101,   2,   3,   4,   5])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.size #returns size of the array - i.e. total no of elements present in an array

5

In [ ]:
arr1.size

8

In [ ]:
arr.shape # returns no of rows and cols

(5,)

In [ ]:
arr1.shape # 2 rows and 4 columns

(2, 4)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(0.3,12.3)) #range function always takes integer values

TypeError: ignored

In [ ]:
np.arange(0.4,10.5,0.2) #this function can take no fraction - floating points number and can generate data

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [ ]:
list(np.arange(0.4,10.5,0.2)) 

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [ ]:
np.linspace(1,10,5) #start, stop and no of data points to generate - divides the range into equal parts as per 3rd parameter

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1,10,20) #start, stop and no of data points to generate - divides the range into equal parts as per 3rd parameter

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1,10,4) #start, stop and no of data points to generate - divides the range into equal parts as per 3rd parameter

array([ 1.,  4.,  7., 10.])

In [ ]:
np.logspace(1,10,5) #this will generate data based on 3 parameters provided same as linspace, default base of log is 10.

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [ ]:
np.logspace(1,10,5, base = 2) #this will generate data based on 3 parameters provided same as linspace

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [ ]:
np.zeros(10) # it will generates array of data of 10 numbers as 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a = np.zeros((4,5)) # this will generate array of data dimention as 4 rows and 5 columns - 2 dim

In [ ]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ndim(a)

2

In [ ]:
b = np.zeros((3,2,5)) # this will generate array of data dimention as 5 rows and 2 columns and  - 3 dim

In [ ]:
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ndim(b)

3

In [ ]:
arr2 = np.ones(10) #returns 10 array elements with 1 as element

In [ ]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr2+1 #each arry element affected by the operaton on array

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [ ]:
arr2*5 #each arry element affected by the operaton on array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.empty((2)) # The numpy.empty() function is used to create a new array of given shape and type, without initializing entries. 
                # It is typically used for large arrays when performance is critical, and the values will be filled in later.

array([-5.73021895e-300,  6.92658056e-310])

In [ ]:
np.eye(6) #Return a 2-D array with ones on the diagonal and zeros elsewhere. - identity matrix (square matrix - no of rows = no of cols)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr3 = np.eye(6) # we can convert this to a pandas dataframe

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr3)

0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0

In [ ]:
np.random.rand(2,3) # returns random numbers as 2 rows and 3 cols - for this data set Mean and SD can be anythig

array([[0.07530255, 0.70370106, 0.12921445],
       [0.84506185, 0.49324853, 0.99176682]])

In [ ]:
np.random.randn(2,3) # returns random numbers as 2 rows and 3 cols - for this data set Mean is 0 and SD is 1 - which is standard normal distribution

array([[-0.25238419,  0.01037622, -1.96863492],
       [-0.68274272,  0.48502513, -0.94189766]])

In [ ]:
arr4 = np.random.randint(1,5, (3,4)) #it generates array of (integer) data from start 1 and end 5 exclusive, with shape as 3 rows and 4 columns

In [ ]:
arr4

array([[4, 3, 2, 4],
       [3, 1, 4, 4],
       [4, 2, 3, 3]])

In [ ]:
arr4.size

12

In [ ]:
arr4.shape

(3, 4)

In [ ]:
arr4.reshape(6,2)

array([[4, 3],
       [2, 4],
       [3, 1],
       [4, 4],
       [4, 2],
       [3, 3]])

In [ ]:
arr4.reshape(2,2,3)

array([[[4, 3, 2],
        [4, 3, 1]],

       [[4, 4, 4],
        [2, 3, 3]]])

In [ ]:
arr5 = np.random.randint(1,10, (5,6))

In [ ]:
arr5

array([[5, 3, 4, 8, 9, 6],
       [2, 1, 4, 8, 3, 6],
       [5, 8, 9, 1, 3, 7],
       [8, 7, 4, 2, 2, 3],
       [8, 5, 9, 2, 6, 8]])

In [ ]:
arr5 > 8 # this condition will return trur or false

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [ ]:
arr5[arr5>8] # returns filtered array based on condition provided

array([9, 9, 9])

In [ ]:
arr5

array([[5, 3, 4, 8, 9, 6],
       [2, 1, 4, 8, 3, 6],
       [5, 8, 9, 1, 3, 7],
       [8, 7, 4, 2, 2, 3],
       [8, 5, 9, 2, 6, 8]])

In [ ]:
arr5[(0,0),(0,1)] 

array([5, 3])

In [ ]:
arr5[2:4, (2,3)] # rows, col

array([[9, 1],
       [4, 2]])

In [ ]:
arr6 = np.random.randint(1,4, (3,3))

In [ ]:
arr7 = np.random.randint(1,4, (3,3))

In [ ]:
arr6

array([[2, 3, 1],
       [1, 2, 3],
       [3, 1, 3]])

In [ ]:
arr7

array([[2, 3, 3],
       [3, 2, 1],
       [2, 1, 2]])

In [ ]:
arr6+arr7 #it performs index wise addtion of elements

array([[4, 6, 4],
       [4, 4, 4],
       [5, 2, 5]])

In [ ]:
arr6*arr7

array([[4, 9, 3],
       [3, 4, 3],
       [6, 1, 6]])

In [ ]:
arr6/0 #infinity output

<ipython-input-85-8dcd99dd37b9>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr6/0 #infinity output


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr8 = np.zeros((3,4))

In [ ]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr8+10 # this is called as broadcasting operations in arrays 

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [ ]:
arr9 = np.array([1,2,3,4])

In [ ]:
arr10 = arr8+arr9 # adds columns wise, no of columns should be same in both arrays


In [ ]:
arr10

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
np.sqrt(arr10)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [ ]:
np.log10(arr10)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999]])

In [ ]:
np.exp(arr10)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [ ]:
np.min(arr10)

1.0

In [ ]:
np.max(arr10)

4.0

In [ ]:
# Array manipulation
ar1 = np.random.randint(1,10, (4,4))

In [ ]:
ar1

array([[2, 4, 1, 9],
       [5, 9, 1, 4],
       [3, 3, 8, 5],
       [1, 4, 5, 1]])

In [ ]:
ar1.reshape(8,2)

array([[2, 4],
       [1, 9],
       [5, 9],
       [1, 4],
       [3, 3],
       [8, 5],
       [1, 4],
       [5, 1]])

In [ ]:
ar1.T # transpose - converts row into col and col into rows - rotate

array([[2, 5, 3, 1],
       [4, 9, 3, 4],
       [1, 1, 8, 5],
       [9, 4, 5, 1]])

In [ ]:
ar1.flatten() #Return a copy of the array collapsed into one dimension. - considers data column wise

array([2, 4, 1, 9, 5, 9, 1, 4, 3, 3, 8, 5, 1, 4, 5, 1])

In [ ]:
np.expand_dims(ar1, axis = 1) #Expand the shape of an array. col wise

# Insert a new axis that will appear at the axis position in the expanded array shape.

array([[[2, 4, 1, 9]],

       [[5, 9, 1, 4]],

       [[3, 3, 8, 5]],

       [[1, 4, 5, 1]]])

In [ ]:
np.expand_dims(ar1, axis = 0) #Expand the shape of an array. row wise

array([[[2, 4, 1, 9],
        [5, 9, 1, 4],
        [3, 3, 8, 5],
        [1, 4, 5, 1]]])

In [ ]:
data = np.array([[1],[2,],[3]])

In [ ]:
np.squeeze(data) # squeeze from higher to lower dimension

array([1, 2, 3])

In [ ]:
np.repeat(data,2) # repeats each elements of array as per no parameter provided

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.roll(data,2) # rotates the elements i.e  0th index+2 = 2 , 1st index + 2 = 3 and so on...

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(ar1) # Extract a diagonal or construct a diagonal array. - here extracted digonal elements of an array 'ar1'

array([2, 9, 8, 1])

In [ ]:
np.diag(np.array([1,2,3,4])) # construct diagonal array from given array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# Numpy - Binary Operators

In [ ]:
ar2 = np.random.randint(1,10, (4,3))

In [ ]:
ar2

array([[8, 8, 7],
       [4, 8, 7],
       [4, 5, 2],
       [6, 7, 5]])

In [ ]:
ar3

array([[12, 12, 14],
       [ 7,  5, 11],
       [ 6,  5,  4],
       [ 9,  1,  9]])

In [ ]:
ar2*ar3

array([[96, 96, 98],
       [28, 40, 77],
       [24, 25,  8],
       [54,  7, 45]])

In [ ]:
ar2/ar3

array([[0.66666667, 0.66666667, 0.5       ],
       [0.57142857, 1.6       , 0.63636364],
       [0.66666667, 1.        , 0.5       ],
       [0.66666667, 7.        , 0.55555556]])

In [ ]:
ar2**ar3

array([[ 68719476736,  68719476736, 678223072849],
       [       16384,        32768,   1977326743],
       [        4096,         3125,           16],
       [    10077696,            7,      1953125]])

In [ ]:
~ar2 # negation operation - converts all to negative value

array([[-9, -9, -8],
       [-5, -9, -8],
       [-5, -6, -3],
       [-7, -8, -6]])

In [ ]:
# Numpy - String operations

In [ ]:
ar4 = np.array(['john','smith','jordan'])

In [ ]:
type(ar4)

numpy.ndarray

In [ ]:
ar4 #here dtype <U6 is string format of the data - unsigned interger

array(['John', 'Smith', 'Jordan'], dtype='<U6')

In [ ]:
np.char.capitalize(ar4) # proper format of string

array(['John', 'Smith', 'Jordan'], dtype='<U6')

In [ ]:
np.char.upper(ar4)

array(['JOHN', 'SMITH', 'JORDAN'], dtype='<U6')

In [ ]:
np.char.title(ar4) #converts very first letter in capital

array(['John', 'Smith', 'Jordan'], dtype='<U6')

In [ ]:
# Mathematical Functions

In [ ]:
ar1

array([[2, 4, 1, 9],
       [5, 9, 1, 4],
       [3, 3, 8, 5],
       [1, 4, 5, 1]])

In [ ]:
np.sin(ar1)

array([[ 0.90929743, -0.7568025 ,  0.84147098,  0.41211849],
       [-0.95892427,  0.41211849,  0.84147098, -0.7568025 ],
       [ 0.14112001,  0.14112001,  0.98935825, -0.95892427],
       [ 0.84147098, -0.7568025 , -0.95892427,  0.84147098]])

In [ ]:
np.cos(ar1)

array([[-0.41614684, -0.65364362,  0.54030231, -0.91113026],
       [ 0.28366219, -0.91113026,  0.54030231, -0.65364362],
       [-0.9899925 , -0.9899925 , -0.14550003,  0.28366219],
       [ 0.54030231, -0.65364362,  0.28366219,  0.54030231]])

In [ ]:
np.tan(ar1)

array([[-2.18503986,  1.15782128,  1.55740772, -0.45231566],
       [-3.38051501, -0.45231566,  1.55740772,  1.15782128],
       [-0.14254654, -0.14254654, -6.79971146, -3.38051501],
       [ 1.55740772,  1.15782128, -3.38051501,  1.55740772]])

In [ ]:
np.power(ar1,2)

array([[ 4, 16,  1, 81],
       [25, 81,  1, 16],
       [ 9,  9, 64, 25],
       [ 1, 16, 25,  1]])

In [ ]:
np.exp(ar1)

array([[7.38905610e+00, 5.45981500e+01, 2.71828183e+00, 8.10308393e+03],
       [1.48413159e+02, 8.10308393e+03, 2.71828183e+00, 5.45981500e+01],
       [2.00855369e+01, 2.00855369e+01, 2.98095799e+03, 1.48413159e+02],
       [2.71828183e+00, 5.45981500e+01, 1.48413159e+02, 2.71828183e+00]])

In [ ]:
np.mean(ar1)

4.0625

In [ ]:
np.median(ar1)

4.0

In [ ]:
np.mod(ar1,2) # modulus divison

array([[0, 0, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 1]])

In [ ]:
np.std(ar1)

2.633171804117612

In [ ]:
np.var(ar1)

6.93359375

In [ ]:
np.min(ar1)

1

In [ ]:
np.max(ar1)

9

In [ ]:
# Numpy - Arithmetic operations

In [ ]:
ar1

array([[2, 4, 1, 9],
       [5, 9, 1, 4],
       [3, 3, 8, 5],
       [1, 4, 5, 1]])

In [ ]:
ar2

array([[8, 8, 7],
       [4, 8, 7],
       [4, 5, 2],
       [6, 7, 5]])

In [ ]:
np.subtract(ar2,ar3)

array([[-4, -4, -7],
       [-3,  3, -4],
       [-2,  0, -2],
       [-3,  6, -4]])

In [ ]:
np.multiply(ar2,ar3)

array([[96, 96, 98],
       [28, 40, 77],
       [24, 25,  8],
       [54,  7, 45]])

In [ ]:
np.divide(ar2,ar3)

array([[0.66666667, 0.66666667, 0.5       ],
       [0.57142857, 1.6       , 0.63636364],
       [0.66666667, 1.        , 0.5       ],
       [0.66666667, 7.        , 0.55555556]])

In [ ]:
np.mod(ar2,ar3)

array([[8, 8, 7],
       [4, 3, 7],
       [4, 0, 2],
       [6, 0, 5]])

In [ ]:
np.square(ar1)

array([[ 4, 16,  1, 81],
       [25, 81,  1, 16],
       [ 9,  9, 64, 25],
       [ 1, 16, 25,  1]])

In [ ]:
np.power(ar2,ar3)

array([[ 68719476736,  68719476736, 678223072849],
       [       16384,        32768,   1977326743],
       [        4096,         3125,           16],
       [    10077696,            7,      1953125]])

In [232]:
# Sort, Search and Counting functions


In [234]:
ar1

array([[2, 4, 1, 9],
       [5, 9, 1, 4],
       [3, 3, 8, 5],
       [1, 4, 5, 1]])

In [237]:
np.sort(ar1) # sort by default row wise - by default ascending order

array([[1, 2, 4, 9],
       [1, 4, 5, 9],
       [3, 3, 5, 8],
       [1, 1, 4, 5]])

In [246]:
np.sort(ar1, axis = 0) # col wise

array([[1, 1, 4, 5],
       [1, 2, 4, 8],
       [1, 3, 5, 9],
       [3, 4, 5, 9]])

In [254]:
np.searchsorted(ar1,3) # Find indices where elements should be inserted to maintain order 

ValueError: ignored

In [257]:
ar = np.array([0,64,0,21,64,0,0,21,4,1,5,101,56,5])

In [260]:
np.count_nonzero(ar) # counts all the elements which are non zero

10

In [262]:
np.where(ar > 10) # return indices of elements based on given condition

(array([ 1,  3,  4,  7, 11, 12]),)

In [265]:
np.where(ar == 0)

(array([0, 2, 5, 6]),)

In [268]:
np.extract(ar > 10, ar) # Return the elements of an array that satisfy the condition given

array([ 64,  21,  64,  21, 101,  56])

In [269]:
# Numpy - Byte swapping

In [272]:
ar.byteswap() # swap original data with bytes which are stored in memory - inplace = True to make changes permanent

array([                  0, 4611686018427387904,                   0,
       1513209474796486656, 4611686018427387904,                   0,
                         0, 1513209474796486656,  288230376151711744,
         72057594037927936,  360287970189639680, 7277816997830721536,
       4035225266123964416,  360287970189639680])

In [273]:
# Numpy Copies and Views

In [285]:
c = ar.view() # New view of array with the same data. - this is like solo copy - changes in one copy also appears in other copy

In [279]:
c

array([  0,  64,   0,  21,  64,   0,   0,  21,   4,   1,   5, 101,  56,
         5])

In [281]:
c[0]  = 111

In [286]:
c

array([111,  64,   0,  21,  64,   0,   0,  21,   4,   1,   5, 101,  56,
         5])

In [287]:
# Numpy - Matrix Library

In [289]:
import numpy.matlib as nm # returns matrix data set

In [291]:
nm.zeros(10) 

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [295]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [299]:
nm.eye(5) # creates matrix with all 1 in diagonal

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [300]:
#Numpy - Linear algebra

In [315]:
a1 = np.array([[1,2],[4,5]])

In [316]:
a1

array([[1, 2],
       [4, 5]])

In [317]:
a2 = np.array([[4,6],[2,7]])

In [318]:
a2

array([[4, 6],
       [2, 7]])

In [321]:
np.dot(a1,a2) #Dot product of two arrays. Specifically, - matrix multilication

array([[ 8, 20],
       [26, 59]])

In [323]:
a1@a2 # same as dot

array([[ 8, 20],
       [26, 59]])